### ISSUE TITLE
Search bar not responding [Bug]: <description>

### ISSUE THREAD

**Issue by Blackbobs** [creative-tutorials/resubase#4]
### Contact Details

ayodejiayodele350@gmail.com 

### Description

```shell
I can't filter through post
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by creative-tutorials** [comment]
# Fix

You can find a fix in the new release note

[bug-patch-fix](https://github.com/creative-tutorials/resubase/releases/tag/8.8.12)
