### ISSUE TITLE
[Notifications] : Users should be alerted of activity via push notifications

### ISSUE THREAD

**Issue by zinzombe-kin** [creative-tutorials/resubase#6]
### Contact Details

kinzinzombe07@gmail.com

### Description

```shell
When something happens in the application, users should be able to receive push notifications like mobile applications are able to do. This will entice users to visit the app or open the website as something new will always be pushed into their notifications
```

### Additional information

```shell
As a start, push notifications will be sent for activity such as upvote or downvote as well as feathering one of their posts.
```

### Is the feature related to the following

New feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by creative-tutorials** [comment]
@zinzombe-kin I'm working really (x3) hard on Notification I've chosen a library/tool for that and an update with notification would be published soon, thanks for opening this issue.

**Comment by zinzombe-kin** [comment]
Alright Timbro

**Comment by creative-tutorials** [comment]
@zinzombe-kin Would you mind looking into this package, and telling me if it's any good 

👇

**[react-push-notification](https://www.npmjs.com/package/react-push-notification)**

**Comment by zinzombe-kin** [comment]
The module is type-safe, it's built in typescript meaning it's blazing fast, it has both web and native support, but thr components are not customizable to the extent that we would like them to be, here's an example of the components
![Uploading 68747470733a2f2f692e696d6775722e636f6d2f536f7266484e612e676966.gif …]()

Overall the package might be a good fit, the installation and initialisation takes less than 5 minutes, the only problem is with the components

**Comment by creative-tutorials** [comment]
@zinzombe-kin The link you sent doesn't work

**Comment by zinzombe-kin** [comment]
It must be a problem with the image I tried to upload. We could create a react context to store all of the notifications, and then when a new notification comes in, we just update that context and then display to the user. For added convenience we could also store this information in the database so that even  if they user logs in from another device then they can see  the notifications  there as well

**Comment by creative-tutorials** [comment]
@zinzombe-kin I will be closing this issue as we have transitioned from being a social community to becoming a search engine.
